export interface FAQ {
  question: string;
  answer: string;
}

export interface HowToStep {
  title: string;
  text: string;
}

export interface Tool {
  slug: string;
  name: string;
  category: 'audio-utility' | 'audio-conversion' | 'video-to-audio';
  from?: string;
  to?: string;
  description: string;
  metaTitle: string;
  metaDescription: string;
  icon: string;
  faq: FAQ[];
  howTo: HowToStep[];
  relatedTools: string[];
}

export const tools: Tool[] = [
  {
    slug: 'audio-cutter',
    name: 'Audio Cutter',
    category: 'audio-utility',
    description: 'Trim and cut audio files directly in your browser.',
    metaTitle: 'Audio Cutter – Trim MP3, WAV Online Free | Dayront',
    metaDescription: 'Cut audio files online without uploading. Trim MP3, WAV, M4A, and more. 100% private.',
    icon: '✂️',
    faq: [
      { question: 'Is it really free?', answer: 'Yes, completely free.' },
      { question: 'Do my files leave my device?', answer: 'No, processing is local.' },
      { question: 'What formats are supported?', answer: 'MP3, WAV, M4A, OGG, FLAC, and more.' },
    ],
    howTo: [
      { title: 'Select your audio file', text: 'Click or drag & drop your audio file.' },
      { title: 'Adjust the cut points', text: 'Use the sliders to set start and end.' },
      { title: 'Download the trimmed audio', text: 'Save your trimmed file.' },
    ],
    relatedTools: ['audio-merger', 'audio-compressor', 'mp3-to-wav'],
  },
  {
    slug: 'audio-merger',
    name: 'Audio Merger',
    category: 'audio-utility',
    description: 'Combine multiple audio files into one.',
    metaTitle: 'Audio Merger – Combine Audio Files Online Free | Dayront',
    metaDescription: 'Merge multiple audio tracks into one file. Supports MP3, WAV, M4A, and more.',
    icon: '🔗',
    faq: [
      { question: 'Can I merge different formats?', answer: 'Yes, mix MP3, WAV, M4A, etc.' },
      { question: 'Is quality preserved?', answer: 'Yes, we avoid unnecessary re-encoding.' },
      { question: 'Is there a file size limit?', answer: 'No hard limit.' },
    ],
    howTo: [
      { title: 'Upload your audio files', text: 'Select two or more files.' },
      { title: 'Arrange the order', text: 'Drag to set playback sequence.' },
      { title: 'Merge and download', text: 'Get your combined file.' },
    ],
    relatedTools: ['audio-cutter', 'audio-compressor', 'wav-to-mp3'],
  },
  {
    slug: 'audio-compressor',
    name: 'Audio Compressor',
    category: 'audio-utility',
    description: 'Reduce audio file size without losing quality.',
    metaTitle: 'Audio Compressor – Reduce Audio File Size Online | Dayront',
    metaDescription: 'Compress MP3, WAV, M4A files in your browser. No uploads, 100% private.',
    icon: '📦',
    faq: [
      { question: 'Will quality suffer?', answer: 'Smart compression keeps audio clear.' },
      { question: 'Is my file safe?', answer: 'Everything happens on your device.' },
      { question: 'Which formats?', answer: 'MP3, WAV, M4A, OGG, FLAC.' },
    ],
    howTo: [
      { title: 'Upload your audio file', text: 'Select the file to compress.' },
      { title: 'Choose compression strength', text: 'Adjust quality vs size.' },
      { title: 'Download compressed file', text: 'Get a lighter file instantly.' },
    ],
    relatedTools: ['volume-booster', 'audio-cutter', 'mp3-to-wav'],
  },
  {
    slug: 'volume-booster',
    name: 'Volume Booster',
    category: 'audio-utility',
    description: 'Make your audio files louder without distortion.',
    metaTitle: 'Volume Booster – Increase Audio Volume Online Free | Dayront',
    metaDescription: 'Make audio files louder instantly. No upload, 100% private.',
    icon: '🔊',
    faq: [
      { question: 'Will it distort?', answer: 'No, we prevent clipping.' },
      { question: 'How much louder?', answer: '+6 dB by default.' },
      { question: 'Supported formats?', answer: 'MP3, WAV, M4A, OGG, FLAC.' },
    ],
    howTo: [
      { title: 'Select your audio file', text: 'Choose a quiet track.' },
      { title: 'Boost the volume', text: 'Safe gain applied.' },
      { title: 'Download louder file', text: 'Save boosted audio.' },
    ],
    relatedTools: ['audio-compressor', 'speed-changer', 'mp3-to-wav'],
  },
  {
    slug: 'speed-changer',
    name: 'Speed Changer',
    category: 'audio-utility',
    description: 'Speed up or slow down audio playback.',
    metaTitle: 'Audio Speed Changer – Change Playback Speed Online Free | Dayront',
    metaDescription: 'Speed up or slow down audio files in your browser. No upload, 100% private.',
    icon: '⏩',
    faq: [
      { question: 'Does it affect pitch?', answer: 'We preserve original pitch.' },
      { question: 'What speeds?', answer: 'From 0.25× to 4×.' },
      { question: 'Is it free?', answer: 'Yes, completely free.' },
    ],
    howTo: [
      { title: 'Upload your audio', text: 'Select file to modify.' },
      { title: 'Choose speed factor', text: 'Pick desired speed.' },
      { title: 'Download altered file', text: 'Get speed-changed audio.' },
    ],
    relatedTools: ['reverse-audio', 'volume-booster', 'audio-cutter'],
  },
  {
    slug: 'reverse-audio',
    name: 'Reverse Audio',
    category: 'audio-utility',
    description: 'Play your audio backwards.',
    metaTitle: 'Reverse Audio – Play Audio Backwards Free Online | Dayront',
    metaDescription: 'Reverse audio files online. No upload needed. 100% private.',
    icon: '↩️',
    faq: [
      { question: 'What does reversing do?', answer: 'Plays sound backwards.' },
      { question: 'Long files?', answer: 'Yes, depends on device speed.' },
      { question: 'Is my file safe?', answer: 'Everything stays on your device.' },
    ],
    howTo: [
      { title: 'Choose your audio file', text: 'Drop an MP3 or WAV.' },
      { title: 'Reverse it', text: 'Click reverse.' },
      { title: 'Download reversed file', text: 'Save backwards audio.' },
    ],
    relatedTools: ['speed-changer', 'audio-cutter', 'mp3-to-ogg'],
  },
  {
    slug: 'stereo-to-mono',
    name: 'Stereo to Mono',
    category: 'audio-utility',
    description: 'Convert stereo audio to mono.',
    metaTitle: 'Stereo to Mono Converter – Free Online Tool | Dayront',
    metaDescription: 'Convert stereo audio to mono instantly. No upload, 100% private.',
    icon: '🔉',
    faq: [
      { question: 'Why convert to mono?', answer: 'Smaller files, same audio in both ears.' },
      { question: 'Quality lost?', answer: 'Combined signal preserves clarity.' },
      { question: 'All formats?', answer: 'MP3, WAV, M4A, FLAC, OGG.' },
    ],
    howTo: [
      { title: 'Upload stereo file', text: 'Select an audio file.' },
      { title: 'Convert automatically', text: 'Mixed to mono.' },
      { title: 'Download mono file', text: 'Save single-channel audio.' },
    ],
    relatedTools: ['audio-cutter', 'volume-booster', 'mp3-to-wav'],
  },
  {
    slug: 'mp3-to-wav',
    name: 'MP3 to WAV',
    category: 'audio-conversion',
    from: 'mp3',
    to: 'wav',
    description: 'Convert MP3 to lossless WAV format.',
    metaTitle: 'MP3 to WAV Converter – Free Online, No Upload | Dayront',
    metaDescription: 'Convert MP3 to lossless WAV in your browser. No upload, 100% private.',
    icon: '🎵',
    faq: [
      { question: 'Does it improve quality?', answer: 'No, preserves original MP3 quality.' },
      { question: 'Why convert to WAV?', answer: 'Preferred for editing and archiving.' },
      { question: 'Is my file safe?', answer: 'All processing is local.' },
    ],
    howTo: [
      { title: 'Upload MP3 file', text: 'Select an MP3.' },
      { title: 'Convert to WAV', text: 'Decoded to uncompressed WAV.' },
      { title: 'Download WAV', text: 'Get lossless file.' },
    ],
    relatedTools: ['wav-to-mp3', 'mp3-to-m4a', 'flac-to-mp3'],
  },
  {
    slug: 'wav-to-mp3',
    name: 'WAV to MP3',
    category: 'audio-conversion',
    from: 'wav',
    to: 'mp3',
    description: 'Convert WAV to MP3 format.',
    metaTitle: 'WAV to MP3 Converter – Free Online, No Upload | Dayront',
    metaDescription: 'Convert WAV to MP3 in your browser. No upload, fully private.',
    icon: '🎵',
    faq: [
      { question: 'How much smaller?', answer: '5-10× smaller than WAV.' },
      { question: 'Will I hear difference?', answer: 'At 320kbps, indistinguishable.' },
      { question: 'Is it free?', answer: 'Yes, unlimited conversions.' },
    ],
    howTo: [
      { title: 'Upload WAV file', text: 'Select a WAV.' },
      { title: 'Convert to MP3', text: 'Compressed to MP3.' },
      { title: 'Download MP3', text: 'Save smaller file.' },
    ],
    relatedTools: ['mp3-to-wav', 'flac-to-mp3', 'audio-cutter'],
  },
  {
    slug: 'm4a-to-mp3',
    name: 'M4A to MP3',
    category: 'audio-conversion',
    from: 'm4a',
    to: 'mp3',
    description: 'Convert M4A audio to MP3 format.',
    metaTitle: 'M4A to MP3 Converter – Free Online, No Upload | Dayront',
    metaDescription: 'Convert M4A to MP3 in your browser. No upload, fully private.',
    icon: '🎵',
    faq: [
      { question: 'Why convert?', answer: 'MP3 is more widely supported.' },
      { question: 'File size?', answer: 'Similar, high-quality MP3 bitrate.' },
      { question: 'Secure?', answer: 'All local processing.' },
    ],
    howTo: [
      { title: 'Upload M4A file', text: 'Select M4A.' },
      { title: 'Convert to MP3', text: 'Re-encoded to MP3.' },
      { title: 'Download MP3', text: 'Get compatible file.' },
    ],
    relatedTools: ['mp3-to-m4a', 'wav-to-mp3', 'volume-booster'],
  },
  {
    slug: 'mp3-to-m4a',
    name: 'MP3 to M4A',
    category: 'audio-conversion',
    from: 'mp3',
    to: 'm4a',
    description: 'Convert MP3 to M4A (AAC) format.',
    metaTitle: 'MP3 to M4A Converter – Free Online, No Upload | Dayront',
    metaDescription: 'Convert MP3 to M4A in your browser. Keep quality, reduce size.',
    icon: '🎵',
    faq: [
      { question: 'Why M4A?', answer: 'Better quality at same bitrate, ideal for Apple.' },
      { question: 'Quality loss?', answer: 'Minimal, high-bitrate AAC encoder.' },
      { question: 'Free?', answer: 'Yes, completely free.' },
    ],
    howTo: [
      { title: 'Select MP3 file', text: 'Choose an MP3.' },
      { title: 'Convert to M4A', text: 'Wrapped in M4A container.' },
      { title: 'Download M4A', text: 'Save for Apple devices.' },
    ],
    relatedTools: ['m4a-to-mp3', 'mp3-to-wav', 'audio-compressor'],
  },
  {
    slug: 'flac-to-mp3',
    name: 'FLAC to MP3',
    category: 'audio-conversion',
    from: 'flac',
    to: 'mp3',
    description: 'Convert FLAC audio to MP3.',
    metaTitle: 'FLAC to MP3 Converter – Free Online, No Upload | Dayront',
    metaDescription: 'Convert FLAC to MP3 in your browser. 100% private, fast and free.',
    icon: '🎵',
    faq: [
      { question: 'Will I lose quality?', answer: 'High-quality 320kbps encoding.' },
      { question: 'Safe?', answer: 'Everything on your device.' },
      { question: 'Batch?', answer: 'Coming soon.' },
    ],
    howTo: [
      { title: 'Upload FLAC file', text: 'Select FLAC.' },
      { title: 'Convert instantly', text: 'Transcoded to MP3.' },
      { title: 'Download MP3', text: 'Save compressed file.' },
    ],
    relatedTools: ['mp3-to-wav', 'ogg-to-mp3', 'audio-cutter'],
  },
  {
    slug: 'ogg-to-mp3',
    name: 'OGG to MP3',
    category: 'audio-conversion',
    from: 'ogg',
    to: 'mp3',
    description: 'Convert OGG audio to MP3 format.',
    metaTitle: 'OGG to MP3 Converter – Free Online, No Upload | Dayront',
    metaDescription: 'Convert OGG to MP3 in your browser. No upload, fully private.',
    icon: '🎵',
    faq: [
      { question: 'Why convert?', answer: 'MP3 is more widely supported.' },
      { question: 'File size change?', answer: 'Slightly larger at high bitrate.' },
      { question: 'Free?', answer: 'Yes, no registration.' },
    ],
    howTo: [
      { title: 'Upload OGG file', text: 'Select OGG Vorbis.' },
      { title: 'Convert to MP3', text: 'Transcoded to MP3.' },
      { title: 'Download MP3', text: 'Get universal file.' },
    ],
    relatedTools: ['mp3-to-ogg', 'flac-to-mp3', 'reverse-audio'],
  },
  {
    slug: 'mp3-to-ogg',
    name: 'MP3 to OGG',
    category: 'audio-conversion',
    from: 'mp3',
    to: 'ogg',
    description: 'Convert MP3 to OGG Vorbis format.',
    metaTitle: 'MP3 to OGG Converter – Free Online, No Upload | Dayront',
    metaDescription: 'Convert MP3 to OGG in your browser. No upload, completely private.',
    icon: '🎵',
    faq: [
      { question: 'Why OGG?', answer: 'Open format, excellent quality.' },
      { question: 'Quality lost?', answer: 'Minimal with high-quality settings.' },
      { question: 'Safe?', answer: 'Local processing.' },
    ],
    howTo: [
      { title: 'Select MP3 file', text: 'Choose MP3.' },
      { title: 'Convert to OGG', text: 'Re-encoded to OGG.' },
      { title: 'Download OGG', text: 'Save open-source file.' },
    ],
    relatedTools: ['ogg-to-mp3', 'mp3-to-wav', 'audio-compressor'],
  },
  {
    slug: 'mp4-to-mp3',
    name: 'MP4 to MP3',
    category: 'video-to-audio',
    from: 'mp4',
    to: 'mp3',
    description: 'Extract MP3 audio from MP4 videos.',
    metaTitle: 'MP4 to MP3 Converter – Extract Audio Free Online | Dayront',
    metaDescription: 'Convert MP4 video to MP3 audio in your browser. No upload, fully private.',
    icon: '🎬',
    faq: [
      { question: 'HD videos?', answer: 'Yes, any MP4 with audio.' },
      { question: 'Uploaded?', answer: 'No, conversion is local.' },
      { question: 'Part of audio?', answer: 'Use Audio Cutter after.' },
    ],
    howTo: [
      { title: 'Upload MP4 video', text: 'Drag & drop MP4.' },
      { title: 'Convert to MP3', text: 'Audio extracted.' },
      { title: 'Download MP3', text: 'Get audio file.' },
    ],
    relatedTools: ['mp4-to-wav', 'webm-to-mp3', 'audio-cutter'],
  },
  {
    slug: 'mov-to-mp3',
    name: 'MOV to MP3',
    category: 'video-to-audio',
    from: 'mov',
    to: 'mp3',
    description: 'Extract MP3 audio from MOV videos.',
    metaTitle: 'MOV to MP3 Converter – Extract Audio Free Online | Dayront',
    metaDescription: 'Convert MOV video to MP3 audio in your browser. No upload, 100% private.',
    icon: '🎬',
    faq: [
      { question: 'iPhone videos?', answer: 'Yes, fully compatible.' },
      { question: 'Quality loss?', answer: 'High-quality encoder.' },
      { question: 'Free?', answer: 'Yes, unlimited.' },
    ],
    howTo: [
      { title: 'Choose MOV file', text: 'Select QuickTime MOV.' },
      { title: 'Extract audio', text: 'Encoded to MP3.' },
      { title: 'Download MP3', text: 'Save audio.' },
    ],
    relatedTools: ['mp4-to-mp3', 'avi-to-mp3', 'speed-changer'],
  },
  {
    slug: 'mkv-to-mp3',
    name: 'MKV to MP3',
    category: 'video-to-audio',
    from: 'mkv',
    to: 'mp3',
    description: 'Extract MP3 audio from MKV videos.',
    metaTitle: 'MKV to MP3 Converter – Extract Audio Free Online | Dayront',
    metaDescription: 'Convert MKV video to MP3 audio in your browser. No upload, completely private.',
    icon: '🎬',
    faq: [
      { question: 'Multi-channel?', answer: 'Downmixed to stereo.' },
      { question: 'Subtitles?', answer: 'Ignored.' },
      { question: 'File size limit?', answer: 'No hard limit.' },
    ],
    howTo: [
      { title: 'Upload MKV video', text: 'Select MKV.' },
      { title: 'Convert to MP3', text: 'Audio extracted.' },
      { title: 'Download MP3', text: 'Get audio file.' },
    ],
    relatedTools: ['avi-to-mp3', 'mp4-to-mp3', 'audio-merger'],
  },
  {
    slug: 'avi-to-mp3',
    name: 'AVI to MP3',
    category: 'video-to-audio',
    from: 'avi',
    to: 'mp3',
    description: 'Extract MP3 audio from AVI videos.',
    metaTitle: 'AVI to MP3 Converter – Extract Audio Free Online | Dayront',
    metaDescription: 'Convert AVI video to MP3 audio in your browser. No upload, 100% private.',
    icon: '🎬',
    faq: [
      { question: 'All AVI files?', answer: 'Yes, with audio track.' },
      { question: 'Uploaded?', answer: 'No, local processing.' },
      { question: 'Multiple?', answer: 'One at a time currently.' },
    ],
    howTo: [
      { title: 'Select AVI file', text: 'Choose AVI video.' },
      { title: 'Extract audio', text: 'Encoded to MP3.' },
      { title: 'Download MP3', text: 'Save audio file.' },
    ],
    relatedTools: ['mkv-to-mp3', 'mov-to-mp3', 'audio-cutter'],
  },
  {
    slug: 'webm-to-mp3',
    name: 'WebM to MP3',
    category: 'video-to-audio',
    from: 'webm',
    to: 'mp3',
    description: 'Extract MP3 audio from WebM videos.',
    metaTitle: 'WebM to MP3 Converter – Extract MP3 Audio Free Online | Dayront',
    metaDescription: 'Convert WebM video to MP3 audio in your browser. No upload, private, and free.',
    icon: '🎬',
    faq: [
      { question: 'Audio-only?', answer: 'Yes, works.' },
      { question: 'Bitrate?', answer: 'High-quality VBR.' },
      { question: 'Safe?', answer: '100% local.' },
    ],
    howTo: [
      { title: 'Upload WebM file', text: 'Select WebM.' },
      { title: 'Convert to MP3', text: 'Audio extracted.' },
      { title: 'Download MP3', text: 'Get audio file.' },
    ],
    relatedTools: ['webm-to-wav', 'mp4-to-mp3', 'audio-compressor'],
  },
  {
    slug: 'mp4-to-wav',
    name: 'MP4 to WAV',
    category: 'video-to-audio',
    from: 'mp4',
    to: 'wav',
    description: 'Extract WAV audio from MP4 videos.',
    metaTitle: 'MP4 to WAV Converter – Extract Audio Free Online | Dayront',
    metaDescription: 'Convert MP4 video to WAV audio in your browser. No upload, fully private.',
    icon: '🎬',
    faq: [
      { question: 'Why WAV?', answer: 'Ideal for editing and archiving.' },
      { question: 'Large files?', answer: 'Yes, depends on device speed.' },
      { question: 'Safe?', answer: 'Everything stays on your computer.' },
    ],
    howTo: [
      { title: 'Choose MP4 video', text: 'Select MP4.' },
      { title: 'Extract WAV', text: 'Uncompressed audio.' },
      { title: 'Download WAV', text: 'Save high-quality audio.' },
    ],
    relatedTools: ['mp4-to-mp3', 'webm-to-wav', 'volume-booster'],
  },
  {
    slug: 'webm-to-wav',
    name: 'WebM to WAV',
    category: 'video-to-audio',
    from: 'webm',
    to: 'wav',
    description: 'Extract WAV audio from WebM videos.',
    metaTitle: 'WebM to WAV Converter – Free Online, No Upload | Dayront',
    metaDescription: 'Extract lossless WAV from WebM files in your browser. No upload, 100% private.',
    icon: '🎬',
    faq: [
      { question: 'Lossless?', answer: 'WAV preserves original audio.' },
      { question: 'WebM videos?', answer: 'Yes, any WebM with audio.' },
      { question: 'Free?', answer: 'Completely free.' },
    ],
    howTo: [
      { title: 'Upload WebM file', text: 'Select WebM.' },
      { title: 'Convert to WAV', text: 'Uncompressed WAV.' },
      { title: 'Download WAV', text: 'Save for editing.' },
    ],
    relatedTools: ['webm-to-mp3', 'mp4-to-wav', 'audio-cutter'],
  },
];